import Link from "next/link";

export type LegalDocumentType = "termos" | "privacidade";
export const LEGAL_LAST_UPDATED = "19 de agosto de 2026";

type Section = { title: string; paragraphs?: React.ReactNode[]; items?: React.ReactNode[] };

export const termsSections: Section[] = [
  { title: "1. Identificação da plataforma", paragraphs: [<>A PlacyHub é uma plataforma digital independente, atualmente administrada por <strong>Vinícius Martins da Costa</strong>, pessoa física responsável por sua operação.</>, <>Para dúvidas, solicitações ou atendimento, o usuário poderá escrever para <a className="legal-link" href="mailto:placyhub@gmail.com">placyhub@gmail.com</a>.</>, "Estes Termos regulam o acesso e a utilização da PlacyHub por visitantes, locatários, anfitriões e demais usuários."] },
  { title: "2. Funcionamento da PlacyHub", paragraphs: ["A PlacyHub conecta pessoas interessadas em reservar espaços para eventos aos anfitriões responsáveis por esses espaços.", "A plataforma oferece recursos para divulgação, pesquisa, reservas, acompanhamento de pagamentos, comunicação, avaliações, denúncias e suporte.", "A PlacyHub não é proprietária dos espaços anunciados e não realiza diretamente os eventos. Cada anfitrião permanece responsável pelo espaço oferecido, sem prejuízo das responsabilidades legalmente atribuídas à PlacyHub."] },
  { title: "3. Cadastro e conta", paragraphs: ["Para criar uma conta, o usuário deverá:"], items: ["ter pelo menos 18 anos e capacidade legal para contratar;", "fornecer informações verdadeiras, completas e atualizadas;", "utilizar seus próprios dados e documentos;", "manter seus contatos atualizados;", "proteger sua senha e comunicar acessos não autorizados."] },
  { title: "4. Verificação dos dados", paragraphs: ["A PlacyHub poderá realizar verificações para confirmar a identidade, prevenir fraudes e proteger os usuários. Poderá solicitar informações ou documentos adicionais antes de liberar funcionalidades, confirmar uma reserva ou autorizar um anúncio.", "As verificações não representam garantia absoluta sobre a identidade ou a conduta de qualquer usuário."] },
  { title: "5. Obrigações do anfitrião", paragraphs: ["O anfitrião declara possuir autorização para anunciar e disponibilizar o espaço e deverá:"], items: ["informar corretamente endereço, preço, capacidade, disponibilidade, estrutura e regras;", "publicar fotos compatíveis com as condições reais;", "cumprir requisitos aplicáveis de segurança, capacidade e funcionamento;", "entregar o espaço nas condições anunciadas e respeitar reservas confirmadas;", "contatar o locatário para combinar acesso, entrega de chaves e orientações;", "comunicar imediatamente qualquer impossibilidade de cumprir a reserva."] },
  { title: "6. Obrigações do locatário", paragraphs: ["O locatário deverá:"], items: ["utilizar o espaço somente para a finalidade informada;", "respeitar horários, capacidade e regras;", "preservar o imóvel, móveis e equipamentos;", "responsabilizar-se por seus convidados;", "não praticar atividades ilegais ou não autorizadas;", "devolver chaves e itens conforme combinado."] },
  { title: "7. Reservas", paragraphs: ["A solicitação não garante automaticamente o espaço. A reserva somente será confirmada após a aprovação do pagamento e a exibição do status “Confirmada” na plataforma.", "Reservas pendentes não garantem a contratação. A PlacyHub poderá analisar ou cancelar operações em caso de falha, duplicidade, indisponibilidade comprovada, suspeita de fraude ou violação destes Termos."] },
  { title: "8. Pagamentos, taxas e repasses", paragraphs: ["Os pagamentos são processados pelo Mercado Pago ou por outro processador informado. A PlacyHub não armazena diretamente os dados completos de cartão inseridos no ambiente do processador.", "Atualmente, o locatário paga taxa de serviço de 5% sobre o valor do espaço e o anfitrião paga comissão de 5% sobre esse valor. O total do locatário e o valor líquido do anfitrião são apresentados antes da contratação e no painel financeiro.", "Mudanças nas taxas serão informadas antes de novas reservas e não afetarão reservas já confirmadas. O repasse seguirá as condições apresentadas na plataforma."] },
  { title: "9. Endereço e contato após a confirmação", paragraphs: ["Antes da confirmação, a PlacyHub poderá apresentar somente a região ou localização aproximada do espaço.", "Após a aprovação, o locatário poderá receber o endereço completo e os dados do anfitrião. O anfitrião poderá receber os dados necessários para identificar e atender o locatário.", "Essas informações deverão ser usadas exclusivamente para executar a reserva."] },
  { title: "10. Comunicação e entrega de chaves", paragraphs: ["Após a confirmação, o anfitrião deverá contatar o locatário em prazo razoável para alinhar acesso, entrega e devolução de chaves, regras específicas e contatos de emergência.", "O locatário deverá manter telefone e e-mail atualizados. Se não houver contato, a parte interessada deverá procurar o suporte da PlacyHub."] },
  { title: "11. Cancelamentos, remarcações e reembolsos", paragraphs: [<>Os cancelamentos seguem a <Link className="legal-link" href="/footer/cancelamentos">Política de Cancelamento</Link>, que integra estes Termos.</>, "As regras comerciais serão aplicadas sem prejuízo dos direitos obrigatórios previstos na legislação brasileira, incluindo o direito de arrependimento quando aplicável.", "Se o anfitrião cancelar sem responsabilidade do locatário, haverá reembolso integral. Remarcações dependem da disponibilidade, da concordância das partes e da confirmação no sistema.", "Reembolsos serão enviados, sempre que possível, ao meio de pagamento original. O prazo poderá depender do Mercado Pago e da instituição financeira."] },
  { title: "12. Força maior", paragraphs: ["Quando acontecimentos imprevisíveis ou inevitáveis impedirem o evento, a PlacyHub poderá auxiliar na remarcação, no cancelamento ou no reembolso, considerando o caso e os direitos previstos na legislação."] },
  { title: "13. Contratação fora da plataforma", paragraphs: ["É proibido usar a PlacyHub para encontrar um espaço e concluir a contratação fora da plataforma com o objetivo de evitar taxas ou controles de segurança. Pagamentos diretos entre usuários não são processados nem acompanhados pela PlacyHub e podem impedir suporte e reembolso."] },
  { title: "14. Avaliações, denúncias e uso indevido", paragraphs: ["As avaliações devem representar experiências reais. É proibido:"], items: ["criar contas falsas ou usar documentos de terceiros;", "fraudar pagamentos, reservas ou reembolsos;", "publicar ameaças, discriminação, conteúdo ilegal ou informações sabidamente falsas;", "explorar falhas técnicas ou interferir no funcionamento da plataforma;", "usar dados de outros usuários para finalidades indevidas."] },
  { title: "15. Suspensão e encerramento", paragraphs: ["A conta poderá ser suspensa ou encerrada em caso de fraude, informações falsas, risco à segurança, descumprimento reiterado, uso ilegal, determinação de autoridade ou violação destes Termos.", "Sempre que possível e apropriado, o usuário será informado e poderá apresentar esclarecimentos."] },
  { title: "16. Propriedade intelectual", paragraphs: ["A marca, identidade visual, sistema e conteúdos próprios da PlacyHub não poderão ser copiados ou utilizados sem autorização.", "Ao enviar fotos e descrições, o usuário declara ter autorização para utilizá-las e permite sua exibição para divulgação do anúncio e operação do serviço."] },
  { title: "17. Disponibilidade e responsabilidades", paragraphs: ["A PlacyHub adotará medidas razoáveis para manter o serviço, mas poderá realizar manutenções ou enfrentar indisponibilidades técnicas.", "O anfitrião responde pela veracidade do anúncio, condições do espaço e cumprimento da reserva. O locatário responde pelo uso do local e pela conduta de seus convidados.", "A PlacyHub responde pelos serviços que presta diretamente, nos limites legais. Estes Termos não eliminam direitos do consumidor nem afastam responsabilidades que não possam ser excluídas."] },
  { title: "18. Privacidade", paragraphs: [<>Os dados pessoais serão tratados conforme a <Link className="legal-link" href="/footer/privacidade">Política de Privacidade</Link> e a legislação. A aceitação destes Termos não substitui consentimentos específicos quando necessários.</>] },
  { title: "19. Alterações", paragraphs: ["Estes Termos poderão ser atualizados por razões legais, comerciais, operacionais ou de segurança. Cada versão indicará a data da última atualização.", "Alterações relevantes serão comunicadas e, quando necessário, dependerão de novo aceite. Não haverá alteração retroativa de reservas confirmadas, salvo para cumprir a legislação."] },
  { title: "20. Atendimento e legislação", paragraphs: [<>Dúvidas, reclamações, cancelamentos e solicitações poderão ser enviados para <a className="legal-link" href="mailto:placyhub@gmail.com">placyhub@gmail.com</a>. O responsável pela operação é <strong>Vinícius Martins da Costa</strong>.</>, "Estes Termos são regidos pela legislação brasileira. Nas relações de consumo, será respeitado o foro legalmente competente, inclusive o domicílio do consumidor quando aplicável."] },
];

export const privacySections: Section[] = [
  { title: "1. Responsável pelo tratamento", paragraphs: [<>A PlacyHub é uma plataforma digital independente, atualmente administrada por <strong>Vinícius Martins da Costa</strong>, responsável pelo tratamento descrito nesta Política.</>, <>Solicitações de privacidade poderão ser enviadas para <a className="legal-link" href="mailto:placyhub@gmail.com">placyhub@gmail.com</a>.</>] },
  { title: "2. Dados pessoais tratados", paragraphs: ["Conforme o uso da plataforma, podemos tratar:"], items: ["nome, e-mail, telefone, nascimento, CPF e foto;", "CEP, rua, número, bairro, cidade e estado;", "reservas, eventos, cancelamentos, avaliações e suporte;", "dados dos espaços, fotos, endereço, disponibilidade e regras;", "informações necessárias para repasses;", "identificação, status e informações gerais de pagamentos;", "IP, navegador, dispositivo e registros de acesso e segurança;", "registros de aceite dos Termos e políticas."] },
  { title: "3. Dados de pagamento", paragraphs: ["Os pagamentos são processados pelo Mercado Pago ou por outro processador informado. A PlacyHub recebe informações para identificar e acompanhar a transação, mas não armazena diretamente os dados completos do cartão fornecidos no ambiente do processador."] },
  { title: "4. Finalidades", paragraphs: ["Os dados poderão ser usados para:"], items: ["criar, verificar e administrar contas;", "publicar espaços e processar reservas;", "confirmar pagamentos e calcular repasses;", "permitir o contato entre as partes após a confirmação;", "enviar comunicações sobre reservas;", "prestar suporte;", "prevenir fraudes e incidentes;", "cumprir obrigações legais e exercer direitos;", "melhorar a segurança e o funcionamento da plataforma."] },
  { title: "5. Bases legais", paragraphs: ["Conforme a finalidade, o tratamento poderá ocorrer para executar contrato ou solicitação, cumprir obrigação legal, exercer direitos, prevenir fraudes, proteger o crédito, atender a interesses legítimos ou com base no consentimento, quando necessário.", "O consentimento não será usado como base genérica e poderá ser revogado quando for a base aplicável."] },
  { title: "6. Compartilhamento", paragraphs: ["Quando necessário, os dados poderão ser compartilhados com:"], items: ["anfitriões ou locatários envolvidos em reserva confirmada;", "Mercado Pago, para pagamentos;", "Supabase, para autenticação, infraestrutura e banco de dados;", "Netlify, para hospedagem e execução;", "Resend ou outro serviço de e-mail;", "prestadores de segurança, suporte e prevenção a fraudes;", "autoridades públicas, por obrigação legal ou determinação válida."] },
  { title: "7. Transferência internacional", paragraphs: ["Alguns fornecedores podem armazenar ou processar informações fora do Brasil. Nesses casos, serão observados os requisitos e as salvaguardas previstos na Lei Geral de Proteção de Dados."] },
  { title: "8. Retenção e exclusão", paragraphs: ["Os dados serão mantidos pelo período necessário para as finalidades informadas, obrigações legais, prevenção a fraudes, prestação de contas e exercício de direitos.", "Depois desse período, serão excluídos ou anonimizados, salvo quando sua conservação for autorizada ou exigida por lei."] },
  { title: "9. Segurança", paragraphs: ["A PlacyHub adotará medidas técnicas e administrativas razoáveis contra acesso não autorizado, perda, alteração ou divulgação indevida.", "Nenhum sistema é totalmente imune a incidentes. Caso ocorra incidente relevante, serão adotadas as providências previstas na legislação."] },
  { title: "10. Cookies", paragraphs: ["A plataforma poderá usar cookies essenciais para login, segurança, preferências e funcionamento. Cookies de análise ou publicidade, caso utilizados, serão informados e, quando necessário, dependerão da escolha do usuário.", "Bloquear cookies essenciais pode impedir o funcionamento de partes da plataforma."] },
  { title: "11. Direitos do titular", paragraphs: ["Nos casos previstos em lei, o usuário poderá solicitar:"], items: ["confirmação e acesso aos dados;", "correção de informações;", "anonimização, bloqueio ou eliminação de dados irregulares;", "portabilidade, conforme regulamentação;", "informações sobre compartilhamentos;", "revogação do consentimento e oposição;", "revisão de decisões exclusivamente automatizadas;", "exclusão da conta, respeitadas as obrigações de conservação."] },
  { title: "12. Como exercer seus direitos", paragraphs: [<>O usuário poderá escrever para <a className="legal-link" href="mailto:placyhub@gmail.com">placyhub@gmail.com</a>. Para proteger a conta, poderá ser solicitada confirmação de identidade.</>] },
  { title: "13. Crianças e adolescentes", paragraphs: ["A plataforma é destinada a maiores de 18 anos e não pretende coletar conscientemente dados de crianças. Contas criadas em desacordo com essa regra poderão ser suspensas."] },
  { title: "14. Alterações", paragraphs: ["Esta Política poderá ser atualizada por razões legais, técnicas ou operacionais. A versão publicada indicará a data da última atualização e mudanças relevantes serão comunicadas quando necessário."] },
];

export function LegalContent({ type, compact = false }: { type: LegalDocumentType; compact?: boolean }) {
  const sections = type === "termos" ? termsSections : privacySections;
  return <div className={compact ? "space-y-4" : "space-y-6"}>{sections.map((section) => (
    <section key={section.title} className={compact ? "space-y-2" : "space-y-3 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800"}>
      <h2 className={compact ? "font-semibold text-gray-900 dark:text-white" : "text-xl font-semibold text-gray-900 dark:text-white md:text-2xl"}>{section.title}</h2>
      {section.paragraphs?.map((paragraph, index) => <p key={index} className="leading-relaxed text-gray-600 dark:text-gray-300">{paragraph}</p>)}
      {section.items && <ul className="ml-6 list-disc space-y-1.5 text-gray-600 dark:text-gray-300">{section.items.map((item, index) => <li key={index}>{item}</li>)}</ul>}
    </section>
  ))}</div>;
}
